server:
  port: 8031

# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.geekhall.bean

# Spring
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3316/db01?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: user01
    password: yy123456

#Eureka配置
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka # Eureka注册中心地址
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka # Eureka注册中心地址
  instance:
    instance-id: springcloud-provider-dept-hystrix-8031  # 修改Eureka上的默认描述信息


# 服务链接中的信息
info:
  app.name: geekhall-springcloud
  company.name: geekhall.cn

